# Generated by Django 3.2.7 on 2021-09-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalURL', models.CharField(max_length=300)),
                ('shortURL', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
